// Sample property data
const PropertiesData = [
    {
        title: "Luxury Family Home",
        price: "$13000/mo",
        location: "1421 San Pedro St, Los Angeles, CA",
        beds: 1,
        baths: 1,
        sqft: 8200,
        type: "Apartment",
        status: "For Sale",
        featured: true,
        img: require("../../../../assets/property.png"),
        agent: "Ali Tufan",
        date: "1 year ago"
    },
    {
        title: "Renovated Apartment",
        price: "$14000/mo",
        location: "1421 San Pedro St, Los Angeles, CA",
        beds: 2,
        baths: 2,
        sqft: 5280,
        type: "Bungalow",
        status: "For Rent",
        featured: true,
        img: require("../../../../assets/property.png"),
        agent: "Ali Tufan",
        date: "1 year ago"
    },
    {
        title: "Renovated Apartment",
        price: "$14000/mo",
        location: "1421 San Pedro St, Los Angeles, CA",
        beds: 2,
        baths: 2,
        sqft: 5280,
        type: "Bungalow",
        status: "For Rent",
        featured: true,
        img: require("../../../../assets/property.png"),
        agent: "Ali Tufan",
        date: "1 year ago"
    },
    {
        title: "Renovated Apartment",
        price: "$14000/mo",
        location: "1421 San Pedro St, Los Angeles, CA",
        beds: 2,
        baths: 2,
        sqft: 5280,
        type: "Bungalow",
        status: "For Rent",
        featured: true,
        img: require("../../../../assets/property.png"),
        agent: "Ali Tufan",
        date: "1 year ago"
    },
    {
        title: "Renovated Apartment",
        price: "$14000/mo",
        location: "1421 San Pedro St, Los Angeles, CA",
        beds: 2,
        baths: 2,
        sqft: 5280,
        type: "Bungalow",
        status: "For Rent",
        featured: true,
        img: require("../../../../assets/property.png"),
        agent: "Ali Tufan",
        date: "1 year ago"
    },
    {
        title: "Renovated Apartment",
        price: "$14000/mo",
        location: "1421 San Pedro St, Los Angeles, CA",
        beds: 2,
        baths: 2,
        sqft: 5280,
        type: "Bungalow",
        status: "For Rent",
        featured: true,
        img: require("../../../../assets/property.png"),
        agent: "Ali Tufan",
        date: "1 year ago"
    },
    {
        title: "Renovated Apartment",
        price: "$14000/mo",
        location: "1421 San Pedro St, Los Angeles, CA",
        beds: 2,
        baths: 2,
        sqft: 5280,
        type: "Bungalow",
        status: "For Rent",
        featured: true,
        img: require("../../../../assets/property.png"),
        agent: "Ali Tufan",
        date: "1 year ago"
    },
    {
        title: "Renovated Apartment",
        price: "$14000/mo",
        location: "1421 San Pedro St, Los Angeles, CA",
        beds: 2,
        baths: 2,
        sqft: 5280,
        type: "Bungalow",
        status: "For Rent",
        featured: true,
        img: require("../../../../assets/property.png"),
        agent: "Ali Tufan",
        date: "1 year ago"
    },
    {
        title: "Renovated Apartment",
        price: "$14000/mo",
        location: "1421 San Pedro St, Los Angeles, CA",
        beds: 2,
        baths: 2,
        sqft: 5280,
        type: "Bungalow",
        status: "For Rent",
        featured: true,
        img: require("../../../../assets/property.png"),
        agent: "Ali Tufan",
        date: "1 year ago"
    },
    {
        title: "Renovated Apartment",
        price: "$14000/mo",
        location: "1421 San Pedro St, Los Angeles, CA",
        beds: 2,
        baths: 2,
        sqft: 5280,
        type: "Bungalow",
        status: "For Rent",
        featured: true,
        img: require("../../../../assets/property.png"),
        agent: "Ali Tufan",
        date: "1 year ago"
    },
    {
        title: "Renovated Apartment",
        price: "$14000/mo",
        location: "1421 San Pedro St, Los Angeles, CA",
        beds: 2,
        baths: 2,
        sqft: 5280,
        type: "Bungalow",
        status: "For Rent",
        featured: true,
        img: require("../../../../assets/property.png"),
        agent: "Ali Tufan",
        date: "1 year ago"
    },
    // Add more property objects here...
];
export default PropertiesData;